//! # ce-patch - one installer for the CE multiplayer/tidiness fixes
//!
//! Run it in a Codename Eagle install folder (or pass the folder as an argument).
//! It patches the three game binaries in place and drops in the replacement
//! iplist.exe, backing up each file once. Idempotent; verifies the expected bytes
//! at every offset and refuses anything it doesn't recognise.
//!
//! - ce.exe      : master-server redirect, cneagle:// self-register + launch,
//!                 chdir to install dir, create logs/ + screenshots/ + saves/,
//!                 redirect error/slave/host/chat logs + screenshots + savegames
//!                 (sg<N>.dat + temp.dat -> saves\), via one .data startup
//!                 routine + string repoints. Version bump "CEBETA v1.43" ->
//!                 "CE v1.50", display + wire protocol (unpatched peers rejected).
//! - LOBBY.EXE   : redirect lobby.log -> logs\, remove the player<N>.txt dumps.
//! - MENUDLL.DLL : redirect menu.log -> logs\, savegames -> saves\.
//! - iplist.exe  : replace the stock prober (finds internet + LAN servers).
//!
//! All patch bytes come from `ce_gen.rs` (generated by `make-ce-patch.js --rust`,
//! verified by disassembly + byte-diff; see design.md). Each edit is
//! `(offset, orig_hex, new_hex)`; an empty `orig` means the target is zero-fill
//! slack. ce.exe additionally gets its `CE_SWAPS` dead-hostname pattern swaps
//! (`master.gamespy.com` -> `ceservers.net`, `codenameeagle.com` ->
//! `codenameeagle.net`).

mod ce_gen;
use ce_gen::{BUNDLED, FILES};
use std::io::{IsTerminal, Read};

#[derive(PartialEq)]
enum St {
    Done,
    Patchable,
    Unexpected,
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

/// State of one `(off, orig_hex, new_hex)` edit against the file. Empty `orig`
/// means slack: pristine iff the span is all zeros.
fn edit_state(data: &[u8], off: usize, orig_hex: &str, new_hex: &str) -> St {
    let new = unhex(new_hex);
    let span = match data.get(off..off + new.len()) {
        Some(s) => s,
        None => return St::Unexpected,
    };
    if span == &new[..] {
        return St::Done;
    }
    if orig_hex.is_empty() {
        if span.iter().all(|&b| b == 0) { St::Patchable } else { St::Unexpected }
    } else if span == &unhex(orig_hex)[..] {
        St::Patchable
    } else {
        St::Unexpected
    }
}

/// State of a dead-hostname pattern swap. `old` still present = patchable (a
/// partial run leaves some occurrences unswapped); `old` gone = done, whether it
/// was already swapped or the build never had it.
fn swap_state(data: &[u8], old: &[u8]) -> St {
    if find(data, old).is_some() {
        St::Patchable
    } else {
        St::Done
    }
}

/// Replace every occurrence of `old` with `new`, zero-padding when `new` is
/// shorter (C strings truncate at the NUL).
fn apply_swap(data: &mut [u8], old: &[u8], new: &[u8]) {
    let mut i = 0;
    while let Some(p) = find(&data[i..], old) {
        let at = i + p;
        for (k, slot) in data[at..at + old.len()].iter_mut().enumerate() {
            *slot = new.get(k).copied().unwrap_or(0);
        }
        i = at + old.len();
    }
}

fn find(hay: &[u8], needle: &[u8]) -> Option<usize> {
    hay.windows(needle.len()).position(|w| w == needle)
}

fn count(hay: &[u8], needle: &[u8]) -> usize {
    let (mut n, mut i) = (0, 0);
    while let Some(p) = find(&hay[i..], needle) {
        n += 1;
        i += p + needle.len();
    }
    n
}

/// Find a file in `dir` by case-insensitive name (Windows is case-insensitive;
/// also lets the tool run on a case-sensitive host for testing).
fn find_file(dir: &std::path::Path, name: &str) -> Option<std::path::PathBuf> {
    std::fs::read_dir(dir).ok()?.flatten().map(|e| e.path()).find(|p| {
        p.file_name().and_then(|n| n.to_str()).is_some_and(|n| n.eq_ignore_ascii_case(name))
    })
}

fn patch_target(dir: &std::path::Path, name: &str, swaps: &[(&[u8], &[u8])], edits: &[(usize, &str, &str)]) -> Result<String, String> {
    let path = match find_file(dir, name) {
        Some(p) => p,
        None => return Ok(format!("{name}: not found, skipped")),
    };
    let mut data = std::fs::read(&path).map_err(|e| format!("{name}: can't read ({e})"))?;

    let mut states: Vec<St> = edits.iter().map(|(o, og, n)| edit_state(&data, *o, og, n)).collect();
    states.extend(swaps.iter().map(|(old, _)| swap_state(&data, old)));
    if states.iter().any(|s| *s == St::Unexpected) {
        return Ok(format!("{name}: unexpected bytes - not a supported build, skipped"));
    }
    if states.iter().all(|s| *s == St::Done) {
        return Ok(format!("{name}: already patched"));
    }

    backup_once(&path)?;
    for (off, _, new_hex) in edits {
        let new = unhex(new_hex);
        data[*off..*off + new.len()].copy_from_slice(&new);
    }
    for (old, new) in swaps {
        apply_swap(&mut data, old, new);
    }
    std::fs::write(&path, &data).map_err(|e| format!("{name}: can't write ({e})"))?;
    Ok(format!("{name}: patched"))
}

fn backup_once(path: &std::path::Path) -> Result<(), String> {
    let bak = path.with_extension(format!(
        "{}.bak",
        path.extension().and_then(|e| e.to_str()).unwrap_or("")
    ));
    if !bak.exists() {
        std::fs::copy(path, &bak).map_err(|e| format!("can't write backup ({e})"))?;
    }
    Ok(())
}

/// Copy a bundled prebuilt binary (sitting next to this tool) into the install
/// dir, backing up the existing one once. Used for the binaries ce-patch ships
/// whole rather than byte-patches: iplist.exe and the patched menudll.dll.
fn install_bundled(dir: &std::path::Path, name: &str) -> Result<String, String> {
    let src = std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|d| d.join(name)))
        .filter(|p| p.exists());
    let src = match src {
        Some(s) => s,
        None => return Ok(format!("{name}: not bundled next to this tool, skipped")),
    };
    let dst = find_file(dir, name).unwrap_or_else(|| dir.join(name));
    if dst.exists() {
        if std::fs::canonicalize(&dst).ok() == std::fs::canonicalize(&src).ok() {
            return Ok(format!("{name}: bundled copy is the target, nothing to do"));
        }
        if std::fs::read(&dst).ok() == std::fs::read(&src).ok() {
            return Ok(format!("{name}: already installed"));
        }
        backup_once(&dst)?;
    }
    std::fs::copy(&src, &dst).map_err(|e| format!("{name}: can't copy ({e})"))?;
    Ok(format!("{name}: installed"))
}

/// Restore the single-player turret to its v1.36 balance (`data4.bin`), SP-only.
/// 1.41 repointed the car-cannon (pillbox/bunker/armored-car turrets) from weapon
/// class 3 to class 15. Single player never worked right after that: SP's weapon
/// table never defines class 15, and MP's class-15 stats are a multiplayer buff
/// (3x damage/projectile-speed) that was never meant for single player. We splice
/// MP's class-14/15 definitions onto the SP table (so the classes exist) and retune
/// the SP class-15 weapon to the 1.36 numbers. Multiplayer (`mdata4.bin`) is never
/// touched, and `car2can.scr` (shared by both modes) is left alone. The table is
/// `+0x78` byte-obfuscated with `Key:Value\n` text records interleaved with binary,
/// so we do length-preserving value edits on the deobfuscated bytes. Idempotent;
/// only acts on the recognised stock/spliced tables (else it skips, never corrupts).
fn patch_data4(dir: &std::path::Path) -> Result<String, String> {
    let sp_path = match find_file(dir, "data4.bin") {
        Some(p) => p,
        None => return Ok("data4.bin: not found, skipped".into()),
    };
    let sp = std::fs::read(&sp_path).map_err(|e| format!("data4.bin: can't read ({e})"))?;
    let deob = |b: &[u8]| -> Vec<u8> { b.iter().map(|x| x.wrapping_sub(0x78)).collect() };
    let ob = |b: &[u8]| -> Vec<u8> { b.iter().map(|x| x.wrapping_add(0x78)).collect() };
    const MARKER: &[u8] = b"15-MOUNTED_LIGHT_MACHINEGUN";
    // length-preserving retune of the class-15 record to 1.36 SP stats (150->45, 30->10)
    const EDITS: [(&[u8], &[u8]); 2] =
        [(b"AmmoSpeed:150.0", b"AmmoSpeed:45.00"), (b"Damage:30.0", b"Damage:10.0")];

    let de = deob(&sp);
    if find(&de, MARKER).is_some() && find(&de, EDITS[0].1).is_some() {
        return Ok("data4.bin: SP turret already restored".into());
    }

    // splice MP's class-14/15 tail onto the SP table if class 15 is absent
    let mut data = sp.clone();
    if find(&de, MARKER).is_none() {
        let mp = match find_file(dir, "mdata4.bin") {
            Some(p) => std::fs::read(&p).map_err(|e| format!("mdata4.bin: can't read ({e})"))?,
            None => return Ok("data4.bin: mdata4.bin not found, SP turret left as-is".into()),
        };
        if mp.len() <= sp.len() {
            return Ok("data4.bin: unrecognised weapon tables, skipped".into());
        }
        data.extend_from_slice(&mp[sp.len()..]);
        if find(&deob(&data), MARKER).is_none() {
            return Ok("data4.bin: unrecognised weapon tables, skipped".into());
        }
    }

    // retune class 15 (each value string is unique to the class-15 record)
    let mut de = deob(&data);
    for (old, new) in EDITS {
        match find(&de, old) {
            Some(_) if count(&de, old) != 1 => {
                return Ok("data4.bin: ambiguous weapon table, skipped".into())
            }
            Some(i) => de[i..i + new.len()].copy_from_slice(new),
            None if find(&de, new).is_some() => {} // already retuned
            None => return Ok("data4.bin: unrecognised class-15 stats, skipped".into()),
        }
    }

    backup_once(&sp_path)?;
    std::fs::write(&sp_path, ob(&de)).map_err(|e| format!("data4.bin: can't write ({e})"))?;
    Ok("data4.bin: single-player turret restored to v1.36 balance".into())
}

/// True for the loose savegame names the stock engine writes into the install
/// root: sg<N>.dat (the numbered slots) and temp.dat (the level-start restart
/// save). The patched binaries read/write these under saves\ instead.
fn is_loose_savegame(name: &str) -> bool {
    let n = name.to_ascii_lowercase();
    if n == "temp.dat" {
        return true;
    }
    n.strip_prefix("sg")
        .and_then(|r| r.strip_suffix(".dat"))
        .is_some_and(|num| !num.is_empty() && num.bytes().all(|b| b.is_ascii_digit()))
}

/// Move savegames the stock game left in the install root into saves\, where
/// the patched binaries look for them. Never overwrites a file already there.
fn migrate_saves(dir: &std::path::Path) -> Result<String, String> {
    let entries = std::fs::read_dir(dir).map_err(|e| format!("saves: can't scan install dir ({e})"))?;
    let saves = dir.join("saves");
    let mut moved = 0;
    for path in entries.flatten().map(|e| e.path()) {
        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) if path.is_file() && is_loose_savegame(n) => n.to_string(),
            _ => continue,
        };
        let dst = saves.join(&name);
        if dst.exists() {
            continue;
        }
        std::fs::create_dir_all(&saves).map_err(|e| format!("saves: can't create dir ({e})"))?;
        std::fs::rename(&path, &dst).map_err(|e| format!("saves: can't move {name} ({e})"))?;
        moved += 1;
    }
    Ok(match moved {
        0 => "saves: no loose savegames to migrate".into(),
        n => format!("saves: moved {n} savegame(s) into saves\\"),
    })
}

fn print_banner() {
    println!("{} v{}", env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION"));
    println!("(c) Espen Hovlandsdal - https://espen.codes/");
    println!("Codename Eagle Nation - https://codenameeagle.net/");
}

fn main() {
    let dir = std::env::args().nth(1).map(std::path::PathBuf::from).unwrap_or_else(|| ".".into());
    print_banner();
    println!("\napplying CE fixes in {}\n", dir.display());

    let mut had_error = false;
    let mut report = |r: Result<String, String>| match r {
        Ok(msg) => println!("  {msg}"),
        Err(e) => {
            eprintln!("  ERROR - {e}");
            had_error = true;
        }
    };
    for (name, swaps, edits) in FILES {
        report(patch_target(&dir, name, swaps, edits));
    }
    report(patch_data4(&dir));
    report(migrate_saves(&dir));
    for name in BUNDLED {
        report(install_bundled(&dir, name));
    }

    // Pause only for double-click runs; scripted runs (installer, CI) get a
    // plain exit so they don't hang waiting for a keypress.
    if std::io::stdin().is_terminal() {
        println!("\nDone. Press Enter to exit...");
        let _ = std::io::stdin().read(&mut [0u8; 1]);
    } else {
        println!("\nDone.");
    }
    if had_error {
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bytes_edit_states_and_apply() {
        let mut d = vec![0xa1, 0xd0, 0x3a, 0x42, 0x00, 0xff];
        assert!(edit_state(&d, 0, "a1d03a4200", "e935000000") == St::Patchable);
        let new = unhex("e935000000");
        d[0..5].copy_from_slice(&new);
        assert!(edit_state(&d, 0, "a1d03a4200", "e935000000") == St::Done);
        assert_eq!(d[5], 0xff, "neighbour untouched");
    }

    #[test]
    fn slack_requires_zeros() {
        let zeros = vec![0u8; 8];
        assert!(edit_state(&zeros, 0, "", "6c6f6700") == St::Patchable); // "log\0"
        let occupied = vec![1u8; 8];
        assert!(edit_state(&occupied, 0, "", "6c6f6700") == St::Unexpected);
    }

    #[test]
    fn swap_zero_pads_shorter_replacement() {
        // master.gamespy.com (18) -> ceservers.net (13): tail zero-padded.
        let mut d = b"xx master.gamespy.com yy".to_vec();
        assert!(swap_state(&d, b"master.gamespy.com") == St::Patchable);
        apply_swap(&mut d, b"master.gamespy.com", b"ceservers.net");
        assert!(find(&d, b"ceservers.net").is_some() && find(&d, b"master.gamespy.com").is_none());
        assert_eq!(&d[3..21], b"ceservers.net\0\0\0\0\0", "tail padded with NULs");
        assert!(swap_state(&d, b"master.gamespy.com") == St::Done);
    }

    #[test]
    fn swap_same_length_all_occurrences() {
        // codenameeagle.com -> codenameeagle.net (equal length): every hit swapped.
        let mut d = b"visit www.codenameeagle.com or codenameeagle.com now".to_vec();
        assert!(swap_state(&d, b"codenameeagle.com") == St::Patchable);
        apply_swap(&mut d, b"codenameeagle.com", b"codenameeagle.net");
        assert!(find(&d, b"codenameeagle.com").is_none());
        assert_eq!(count(&d, b"codenameeagle.net"), 2);
        assert!(swap_state(&d, b"codenameeagle.com") == St::Done);
    }

    #[test]
    fn wrong_build_is_unexpected() {
        let d = vec![0x55u8; 0x100];
        assert!(edit_state(&d, 0, "a1d0", "e935") == St::Unexpected);
    }

    #[test]
    fn data4_splices_and_retunes_sp_turret() {
        // synthetic obfuscated tables: SP lacks class 15; MP defines it (150/30).
        let ob = |b: &[u8]| -> Vec<u8> { b.iter().map(|x| x.wrapping_add(0x78)).collect() };
        let deob = |b: &[u8]| -> Vec<u8> { b.iter().map(|x| x.wrapping_sub(0x78)).collect() };
        let sp = b"STOCK-SP-14-WEAPONS-no-class-15-here".to_vec();
        let mut mp = sp.clone();
        mp.extend_from_slice(
            b"|14-HELI|15-MOUNTED_LIGHT_MACHINEGUN\nAmmoSpeed:150.0\nDamage:30.0\n",
        );
        let dir = std::env::temp_dir().join(format!("cepatch_data4_test_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("data4.bin"), ob(&sp)).unwrap();
        std::fs::write(dir.join("mdata4.bin"), ob(&mp)).unwrap();

        let msg = patch_data4(&dir).unwrap();
        assert!(msg.contains("restored"), "unexpected: {msg}");
        let out = deob(&std::fs::read(dir.join("data4.bin")).unwrap());
        assert!(find(&out, b"15-MOUNTED_LIGHT_MACHINEGUN").is_some(), "class 15 spliced");
        assert!(find(&out, b"AmmoSpeed:45.00").is_some(), "speed retuned");
        assert!(find(&out, b"Damage:10.0").is_some(), "damage retuned");
        assert!(find(&out, b"AmmoSpeed:150.0").is_none() && find(&out, b"Damage:30.0").is_none());
        // MP untouched
        assert_eq!(std::fs::read(dir.join("mdata4.bin")).unwrap(), ob(&mp), "MP table untouched");
        // idempotent
        assert!(patch_data4(&dir).unwrap().contains("already"), "second run is a no-op");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn migrates_only_loose_savegames() {
        assert!(is_loose_savegame("sg0.dat") && is_loose_savegame("SG12.DAT"));
        assert!(is_loose_savegame("temp.dat") && is_loose_savegame("TEMP.DAT"));
        assert!(!is_loose_savegame("sg.dat") && !is_loose_savegame("sgx.dat"));
        assert!(!is_loose_savegame("objects.dat") && !is_loose_savegame("sg0.dat.bak"));

        let dir = std::env::temp_dir().join(format!("cepatch_saves_test_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("sg0.dat"), b"slot0").unwrap();
        std::fs::write(dir.join("sg3.dat"), b"slot3").unwrap();
        std::fs::write(dir.join("temp.dat"), b"temp").unwrap();
        std::fs::write(dir.join("objects.dat"), b"not a save").unwrap();
        // an existing saves\ file must never be overwritten
        std::fs::create_dir_all(dir.join("saves")).unwrap();
        std::fs::write(dir.join("saves").join("sg3.dat"), b"newer").unwrap();

        let msg = migrate_saves(&dir).unwrap();
        assert!(msg.contains("moved 2"), "unexpected: {msg}");
        assert_eq!(std::fs::read(dir.join("saves").join("sg0.dat")).unwrap(), b"slot0");
        assert_eq!(std::fs::read(dir.join("saves").join("temp.dat")).unwrap(), b"temp");
        assert_eq!(std::fs::read(dir.join("saves").join("sg3.dat")).unwrap(), b"newer", "kept");
        assert!(dir.join("sg3.dat").exists(), "unmigrated loose file left in place");
        assert!(dir.join("objects.dat").exists(), "non-save untouched");
        // second run: only the blocked sg3.dat is left, nothing moves
        assert!(migrate_saves(&dir).unwrap().contains("no loose savegames"));
        std::fs::remove_dir_all(&dir).ok();
    }

    // --- provenance tests --------------------------------------------------
    //
    // Prove the shipped binaries in game/common are EXACTLY "stock 1.43 + this
    // tool's edits" and nothing else: copy the pristine 1.43 file into a temp
    // dir, run the same patch routine main() runs, and require byte equality
    // with the shipped file. ce.exe additionally gets the icon embedded via
    // scripts/embed-ce-icon.js, the same final step that produces the shipped
    // binary (so this test needs `node` too). #[ignore]d because they need
    // local paths:
    //
    //   CE_PRISTINE_143=/path/to/pristine/1.43 \
    //   CE_GAME_COMMON=/path/to/repo/game/common \
    //   cargo test -- --ignored provenance

    fn provenance_dir(var: &str) -> std::path::PathBuf {
        let v = std::env::var(var).unwrap_or_else(|_| {
            panic!(
                "{var} must be set for the provenance tests. Run them as:\n  \
                 CE_PRISTINE_143=/path/to/pristine/1.43 \
                 CE_GAME_COMMON=/path/to/repo/game/common \
                 cargo test -- --ignored provenance"
            )
        });
        let dir = std::path::PathBuf::from(v);
        assert!(dir.is_dir(), "{var}={} is not a directory", dir.display());
        dir
    }

    /// Copy `name` (located case-insensitively, pristine installs use
    /// e.g. LOBBY.EXE) from `src_dir` into `dst_dir` under the canonical name.
    fn copy_in(src_dir: &std::path::Path, name: &str, dst_dir: &std::path::Path) {
        let src = find_file(src_dir, name)
            .unwrap_or_else(|| panic!("{name} not found in {}", src_dir.display()));
        std::fs::copy(&src, dst_dir.join(name)).unwrap();
    }

    fn read_shipped(common: &std::path::Path, name: &str) -> Vec<u8> {
        let path = find_file(common, name)
            .unwrap_or_else(|| panic!("{name} not found in CE_GAME_COMMON ({})", common.display()));
        std::fs::read(path).unwrap()
    }

    /// Byte equality with an actionable failure message: differing-byte count
    /// (length differences counted) and the first differing offset.
    fn assert_same_bytes(name: &str, produced: &[u8], shipped: &[u8]) {
        if produced == shipped {
            return;
        }
        let n = produced.len().min(shipped.len());
        let differing = (0..n).filter(|&i| produced[i] != shipped[i]).count()
            + produced.len().abs_diff(shipped.len());
        let first = (0..n).find(|&i| produced[i] != shipped[i]).unwrap_or(n);
        panic!(
            "{name}: patched pristine 1.43 differs from shipped game/common copy: \
             {differing} byte(s) differ (patched len {} vs shipped len {}), \
             first difference at offset {first:#x}",
            produced.len(),
            shipped.len()
        );
    }

    /// Shared body for the byte-patched binaries (ce.exe, lobby.exe): patch a
    /// pristine copy via `patch_target` with the generated `FILES` tables -
    /// the exact code path main() uses - and compare with game/common.
    ///
    /// `embed_icon` additionally runs scripts/embed-ce-icon.js on the patched
    /// copy (ce.exe only), the same final step that produces the shipped exe.
    /// The byte patch is append-safe: the icon lands in a trailing .rsrc
    /// section and leaves the patched .text/.rdata/.data untouched.
    fn provenance_byte_patched(name: &str, embed_icon: bool) {
        let pristine = provenance_dir("CE_PRISTINE_143");
        let common = provenance_dir("CE_GAME_COMMON");
        let dir = std::env::temp_dir()
            .join(format!("cepatch_provenance_{}_{}", name.replace('.', "_"), std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        copy_in(&pristine, name, &dir);

        let (_, swaps, edits) = FILES
            .iter()
            .find(|(n, _, _)| *n == name)
            .unwrap_or_else(|| panic!("{name} not in generated FILES table"));
        let msg = patch_target(&dir, name, swaps, edits).unwrap();
        assert_eq!(msg, format!("{name}: patched"), "pristine copy must be recognised");

        if embed_icon {
            let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
            let script = manifest.join("../scripts/embed-ce-icon.js");
            let status = std::process::Command::new("node")
                .arg(&script)
                .arg(dir.join(name))
                .arg(manifest.join("assets/ce.ico")) // group 1: default icon
                .arg(manifest.join("assets/cespy.ico")) // group 2: selectable alternate
                .status()
                .unwrap_or_else(|e| {
                    panic!("can't run node (required to embed the icon into {name}): {e}")
                });
            assert!(status.success(), "embed-ce-icon.js failed: {status}");
        }

        let produced = std::fs::read(dir.join(name)).unwrap();
        let shipped = read_shipped(&common, name);
        std::fs::remove_dir_all(&dir).ok();
        assert_same_bytes(name, &produced, &shipped);
    }

    #[test]
    #[ignore] // needs CE_PRISTINE_143 + CE_GAME_COMMON (+ node), see comment above
    fn provenance_ce_exe() {
        provenance_byte_patched("ce.exe", true);
    }

    #[test]
    #[ignore] // needs CE_PRISTINE_143 + CE_GAME_COMMON, see comment above
    fn provenance_lobby_exe() {
        provenance_byte_patched("lobby.exe", false);
    }

    #[test]
    #[ignore] // needs CE_PRISTINE_143 + CE_GAME_COMMON, see comment above
    fn provenance_data4_bin() {
        let pristine = provenance_dir("CE_PRISTINE_143");
        let common = provenance_dir("CE_GAME_COMMON");
        let dir = std::env::temp_dir()
            .join(format!("cepatch_provenance_data4_bin_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        copy_in(&pristine, "data4.bin", &dir);
        // patch_data4 splices the class-14/15 tail from mdata4.bin beside data4.bin
        copy_in(&pristine, "mdata4.bin", &dir);

        let msg = patch_data4(&dir).unwrap();
        assert!(msg.contains("restored"), "pristine data4.bin must be recognised: {msg}");

        let produced = std::fs::read(dir.join("data4.bin")).unwrap();
        let shipped = read_shipped(&common, "data4.bin");
        std::fs::remove_dir_all(&dir).ok();
        assert_same_bytes("data4.bin", &produced, &shipped);
    }

    #[test]
    #[ignore] // needs CE_PRISTINE_143 + CE_GAME_COMMON (+ node), see comment above
    fn provenance_menudll_dll() {
        // menudll.dll is a bundled prebuilt, not byte-patched by this tool; its
        // provenance proof is the generator script: stock 1.43 MENUDLL.DLL run
        // through menudll/make-menudll-patch.js must equal the shipped file.
        let pristine = provenance_dir("CE_PRISTINE_143");
        let common = provenance_dir("CE_GAME_COMMON");
        let dir = std::env::temp_dir()
            .join(format!("cepatch_provenance_menudll_dll_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let stock = find_file(&pristine, "menudll.dll")
            .unwrap_or_else(|| panic!("MENUDLL.DLL not found in {}", pristine.display()));
        let out = dir.join("menudll.dll");
        let script = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("menudll")
            .join("make-menudll-patch.js");

        let status = std::process::Command::new("node")
            .arg(&script)
            .arg(&stock)
            .arg("-o")
            .arg(&out)
            .status()
            .unwrap_or_else(|e| {
                panic!("can't run node (required by {}): {e}", script.display())
            });
        assert!(status.success(), "make-menudll-patch.js failed: {status}");

        let produced = std::fs::read(&out).unwrap();
        let shipped = read_shipped(&common, "menudll.dll");
        std::fs::remove_dir_all(&dir).ok();
        assert_same_bytes("menudll.dll", &produced, &shipped);
    }

    #[test]
    fn generated_tables_are_sane() {
        // ce.exe + lobby.exe are byte-patched; iplist/menudll/cemusic are bundled.
        assert_eq!(FILES.len(), 2);
        assert_eq!(BUNDLED, &["iplist.exe", "menudll.dll", "cemusic.dll"]);
        for (_, _, edits) in FILES {
            for (_, orig, new) in *edits {
                assert!(orig.len() % 2 == 0 && new.len() % 2 == 0 && !new.is_empty());
            }
        }
    }
}
